require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.impatient"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.telescope"
require "user.nvimtree"
require "user.comment"
require "user.blankline"
require "user.autopairs"
require "user.gitsigns"
require "user.lualine"
require "user.toggleterm"

